name: Sync backend to Hugging Face Space

on:
  push:
    branches:
      - separate-files

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Sync backend folder to Hugging Face Space
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: berlynguci/thesis-backend
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: docker
          subdirectory: backend